sudo: false
language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - nightly
env:
    - FRAMEWORK=django~=1.6.0
    - FRAMEWORK=django~=1.7.0
    - FRAMEWORK=django~=1.8.0
    - FRAMEWORK=django~=1.9.0
    - FRAMEWORK=flask~=0.10.0
install:
    - pip install -q "${FRAMEWORK}"
    - pip install -q -r dev_requirements.txt
    - pip install -q -e .
script:
    - nosetests --nocapture
